import type { LucideIcon } from "lucide-react";
import {
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Car,
  CircleHelp,
  ClipboardList,
  Clock,
  Cpu,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  Hand,
  HeartHandshake,
  Home,
  LayoutTemplate,
  Lightbulb,
  Megaphone,
  MessageCircle,
  Monitor,
  Palette,
  PawPrint,
  RefreshCw,
  Search,
  Shirt,
  ShoppingBag,
  Sparkles,
  Sprout,
  Store,
  TestTube,
  Users,
  UtensilsCrossed,
  Wallet,
  Wrench,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  online: Monitor,
  physical: Store,
  both: RefreshCw,
  notSure: CircleHelp,
  food: UtensilsCrossed,
  fashion: Shirt,
  beauty: Sparkles,
  cars: Car,
  sports: Dumbbell,
  technology: Cpu,
  design: Palette,
  photography: Camera,
  gaming: Gamepad2,
  games: Gamepad2,
  pets: PawPrint,
  animals: PawPrint,
  education: GraduationCap,
  shopping: ShoppingBag,
  other: CircleHelp,
  under500: Wallet,
  "500to2000": Wallet,
  "2000to5000": Wallet,
  "5000to15000": Wallet,
  over15000: Wallet,
  under1h: Clock,
  "1to3h": Clock,
  "3to6h": Clock,
  mostOfDay: Clock,
  independentAnalytical: Brain,
  flexibleCreative: Palette,
  structuredDirect: ClipboardList,
  collaborativeSocial: Users,
  tech: Cpu,
  marketing: Megaphone,
  people: MessageCircle,
  ops: Briefcase,
  craft: Hand,
  safeSmall: Sprout,
  learnByDoing: TestTube,
  sideIncome: Wallet,
  growFast: Briefcase,
  enjoy: Users,
  some: MessageCircle,
  dontMind: MessageCircle,
  limited: Home,
  minimal: Home,
  none: Monitor,
  alone: Home,
  onePerson: Home,
  flexible: RefreshCw,
  team: Users,
  money: Wallet,
  big: Lightbulb,
  freedom: Home,
  creativity: Palette,
  helping: HeartHandshake,
  first: Sprout,
  smallProjects: LayoutTemplate,
  experienced: Briefcase,
  hasProject: Store,
  now: Clock,
  withinMonth: Calendar,
  later: Calendar,
  exploring: Search,
  services: Wrench,
  digital: Monitor,
  health: Sparkles,
};

export function quizOptionIcon(value: string): LucideIcon {
  return MAP[value] ?? CircleHelp;
}
