/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        page: "var(--c-page)",
        surface: "var(--c-surface)",
        elevated: "var(--c-elevated)",
        fg: "var(--c-fg)",
        muted: "var(--c-muted)",
        subtle: "var(--c-subtle)",
        line: "var(--c-line)",
        "line-strong": "var(--c-line-strong)",
        accent: "var(--c-accent)",
        "accent-hover": "var(--c-accent-hover)",
        "accent-fg": "var(--c-accent-fg)",
        "accent-soft": "var(--c-accent-soft)",
        "accent-text": "var(--c-accent-text)",
        ok: "var(--c-ok)",
        "ok-soft": "var(--c-ok-soft)",
        warn: "var(--c-warn)",
        "warn-soft": "var(--c-warn-soft)",
        danger: "var(--c-danger)",
        "danger-soft": "var(--c-danger-soft)",
        fikra: {
          50: "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          300: "#c4b5fd",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
          900: "#4c1d95",
        },
        azure: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        ink: {
          50: "var(--c-page)",
          100: "var(--c-accent-soft)",
          200: "var(--c-line)",
          300: "var(--c-line-strong)",
          400: "var(--c-subtle)",
          500: "var(--c-muted)",
          600: "var(--c-muted)",
          700: "var(--c-fg)",
          800: "var(--c-fg)",
          900: "var(--c-fg)",
        },
      },
      fontFamily: {
        sans: ["var(--font-ar)", "var(--font-en)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "10px",
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
        "2xl": "14px",
        "3xl": "16px",
      },
      boxShadow: {
        card: "0 1px 2px rgb(18 20 26 / 0.04)",
        float: "0 8px 24px rgb(18 20 26 / 0.06)",
        soft: "0 1px 2px rgb(18 20 26 / 0.04)",
      },
      maxWidth: {
        content: "72rem",
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, to: { opacity: "1" } },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        heroWordIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        heroWordOut: {
          "0%": { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(-8px)" },
        },
      },
      animation: {
        "fade-in": "fade-in .4s ease-out forwards",
        "fade-up": "fade-up .45s ease-out forwards",
      },
    },
  },
  plugins: [],
};
